swagger: "2.0"
info:
  description: "comunicación standar entre servicios especializados "
  version: "1.0.0"
  title: "Swagger Taller MVA Microservicios"
  contact:
    email: "yeselin@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
  - "http"
basePath: "/barclays"
host: "127.0.0.1"    
tags:
- name: "barclays"
  description: "Ejemplo de MicroServicios - caso de estudio modelado de arquitectura."
paths:
  /paymentService/query/{idFactura}:
    get:
      tags:
        - "Consulta Factura"
      summary: "Consulta de factura de servicios públicos"
      operationId: "query"
      produces:
        - "application/json"
      parameters:
        - name: "idFactura"
          in: "path"
          description: "Id de de la factura a consultar"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "información de la factura"
          schema:
            $ref: '#/definitions/queryRS'
        404:
          description: "Not found"
  /paymentService/payment:
    post:
      tags:
      - "Pago de Factura"
      summary: "Servicio de pagos"
      description: ""
      operationId: "payment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Mensajeria que se recibe en el cuerpo de la peticion para el servicio de Pagos"
        required: true
        schema:
          $ref: "#/definitions/paymentRQ"
      responses:
        200:
          description: "Respuesta del pago efectuado"
          schema:
            $ref: '#/definitions/paymentRS'
        404:
          description: "Not found"
        405:
          description: "Invalid input"
definitions:
  queryRS:
    type: "object"
    properties:
        serviceId:
          type: "number"
          description: Identificador de la factura
          example: 333
        service:
          type: "string"
          description: Nombre del servicio público
          example: Agua, Electricidad, etc.
        value:
          type: "number"
          description: valor de la factura
          example: 78000
    example: 
      serviceId: 4449234
      value: 28548.773
      service: agua
      
  paymentRQ:
    type: "object"
    properties:
        serviceId:
          type: "number"
          description: Identificador de la factura
          example: 111345
        value:
          type: "string"
          description: valor de la factura
          example: '78000'
  paymentRS:
    type: "object"
    properties:
        serviceId:
          type: "number"
          description: Identificador de la factura
          example: 111235
        messageStatus:
          type: "string"
          description: Descripción del estado del pago
          example: "Factura Pagada Exitosamente"
