version: '2'
services:
  orchestrator:
    image: orchestrator
    ports:
      - "9111:9111"
  routing:
    image: routing
    ports: 
      - "9222:9222"
  dispatcher:
    image: dispatcher
    ports: 
      - "9333:9333"
  transform:
    image: transform
    ports: 
      - "9444:9444"
