# Set the base image
FROM openjdk
# Dockerfile author / maintainer 
MAINTAINER makayppe

# Update application repository list 
ENV SERVER_PORT=9444
WORKDIR /
COPY transform-0.0.1-SNAPSHOT.jar barclaysTransformService.jar
EXPOSE 9444
CMD ["java","-jar","barclaysTransformService.jar"]

