swagger: '2.0'
info:
  description: 'Comunicación estandar entre servicios especializados '
  version: 1.0.0
  title: Swagger Taller MVA Microservicios
  contact:
    email: yeselin@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
basePath: /barclays
host: 127.0.0.1:9444
tags:
  - name: barclays
    description: Ejemplo de MicroServicios - caso de estudio modelado de arquitectura.
paths:
 '/transform/v1':
    post:
      tags:
        - 'Traducción de Mensajes'
      summary: 'obtiene un mensaje y lo traduce al esquema adecuado para el proveedor y de éste a mensajes internos.'
      description: ''
      operationId: InternalService
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: InternalServiceRQType
          description: >-
            Mensajeria que se recibe en el cuerpo de la peticion para el
            servicio de Transformación
          required: false
          schema:
              type: object
              $ref: '#/definitions/InternalServiceRQType'
      responses:
        '405':
          description: Invalid input
definitions:
  InternalServiceRQType:
    type: object
    properties:
      internalRequest :
        type: object
        description: recibe el objeto de solicitud interna
        properties :
          operation:
            type : string
            description : la operación que se va realizar Pago o Consulta
            example : 'Consultar'
          message :
            type : string
            description : transporta el mensaje interno a traducir
            example : '{\"serviceId\": 123,\"value\": 80637.02859054488}'
          massageType :
            type : string
            description : contiene el tipo de mensaje REST o SOAP
            example : 'REST'
          provider:
            type: object
            description : datos del proveedor  
            properties :
              id :
                type : number
                description : identificador de proveedor de Servicio publico
                example : 333
              name :
                type : string
                description : la descripcion del servicio publico
                example : 'Agua'
              description : 
                type : string
                description : texto descriptivo
                example : 'servicio de agua'
              enable :
                type : boolean
                description : indica si el servicio esta activo o no
                example : true
              operation :
                type : string
                description : indica si es una Consulta o es el Pago
                example : 'Consultar'
              rest : 
                type:  object
                properties:
                  endPoint : 
                    type : string
                    description : el endpoint del proveedor de servicio
                    example : 'http://localhost:9090/servicios/pagos/v1/payments'
                  method:
                    type : string 
                    description : indica el metodo http a utilizar GET,POST,PUT, etc.
                    example : 'POST'
              soap :
                type : object
                properties:
                  endpoint:
                    type : string
                    description : direccion del endpoint
                    example : 'http://localhost:7070/w1-soap-svr/PagosServiceService?wsdl'
                  targetNameSpace:
                    type : string
                    description : espacio de nombre objetivo
                    example : 'http://www.servicios.co/pagos/schemas'
                  serviceName :
                    type : string
                    description : nombre del servicio
                    example : 'PagosServiceService'
                  servicePort :
                    type : string 
                    description : puerto de comunicacion del servicio
                    example : 'PagosInerface'
                  operation :
                    type : string
                    description : operacion a realizar Consultar o Pagar
                    example : 'Consultar'
      serviceType:
        type: number
        description: tipo de servicio
        example: 333
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'