swagger: '2.0'
info:
  description: 'Comunicación estandar entre servicios especializados '
  version: 1.0.0
  title: Swagger Taller MVA Microservicios
  contact:
    email: yeselin@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
basePath: /barclays
host: 127.0.0.1:9333
tags:
  - name: barclays
    description: Ejemplo de MicroServicios - caso de estudio modelado de arquitectura.
paths:
 '/dispatcher/v1':
    post:
      tags:
        - 'Dispatcher '
      summary: 'Encargado de comunicación de mensajes con el proveedor y los servicios internos'
      description: 'Para la peticion InternalServiceRQType y para la Respuesta InternalServiceRSType'
      operationId: internalServiceRQ
      consumes:
        - application/json
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: >-
           esquema de la solicitud o peticion interna entre servicios
          required: true
          schema:
            $ref: '#/definitions/InternalRequestType'
      responses:
        '405':
          description: Invalid input
definitions:
  InternalRequestType:
    type: object
    properties:
      operation:
        type: string
        description: indica si es Pago o es Consulta
        example: 'Pago'
      message:
        type: string
        description: mensaje con la informacion a transmitir 
        example: '{services:222,message:uno}'
      massageType:
        type: string
        description: indica el tipo de conexion de servicio REST o SOAP
        example: 'REST'
      provider:
        type: string
        description: indica el proveedor del servicio
        example: 'agua'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
