swagger: '2.0'
info:
  description: 'comunicación standar entre servicios especializados '
  version: 1.0.0
  title: Swagger Taller MVA Microservicios
  contact:
    email: yeselin@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
basePath: /barclays
host: 127.0.0.1:9222
tags:
  - name: barclays
    description: Ejemplo de MicroServicios - caso de estudio modelado de arquitectura.
paths:
  '/routing/v1/{id}/{operation}':
    get:
      tags:
        - Enruta al Endpoint
      summary: consulta el endpoint segun la necesidad del id del servicio enviado
      operationId: checkLoan
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id del servicio (agua,luz,telefono, etc)
          required: true
          type: integer
          format: int64
        - name: operation
          in: path
          description: operacion a realizar Consulta/Pago
          required: true
          type: string
      responses:
        '200':
          description: mensaje interno con el proveedor
          schema:
            type: object
            $ref: '#/definitions/provider'
        '400':
          description: Bad request

definitions:
  provider:
    type: object
    properties:
      id :
        type : number
        description : identificador de proveedor de Servicio publico
        example : 333
      name :
        type : string
        description : la descripcion del servicio publico
        example : 'Agua'
      description : 
        type : string
        description : texto descriptivo
        example : 'servicio de agua'
      enable :
        type : boolean
        description : indica si el servicio esta activo o no
        example : true
      operation :
        type : string
        description : indica si es una Consulta o es el Pago
        example : 'Consultar'
      rest : 
        type:  object
        properties:
          endPoint : 
            type : string
            description : el endpoint del proveedor de servicio
            example : 'http://localhost:9090/servicios/pagos/v1/payments'
          method:
            type : string 
            description : indica el metodo http a utilizar GET,POST,PUT, etc.
            example : 'POST'
      soap :
        type : object
        properties:
          endpoint:
            type : string
            description : direccion del endpoint
            example : 'http://localhost:7070/w1-soap-svr/PagosServiceService?wsdl'
          targetNameSpace:
            type : string
            description : espacio de nombre objetivo
            example : 'http://www.servicios.co/pagos/schemas'
          serviceName :
            type : string
            description : nombre del servicio
            example : 'PagosServiceService'
          servicePort :
            type : string 
            description : puerto de comunicacion del servicio
            example : 'PagosInerface'
          operation :
            type : string
            description : operacion a realizar Consultar o Pagar
            example : 'Consultar'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'